### ISSUE TITLE
BUG Audio Receive - Cannot Audio Capture

### ISSUE THREAD

**Issue by SCarns** [rgleason/weatherfax_pi#77] opened 2022-05-05 00:51 UTC
Cannot do an audio capture on Mac OS X Catalina. Audio capture sometimes crashes OpenCPN. Preferences dialog won't let me select an input. Also, preferences won't let me choose between "Meters" and "Feet".

**Comment by SCarns** [comment] 2022-05-05 01:08
Also, unable to "Update Sources" to see new locations, such as French Polynesia.

**Comment by rgleason** [comment] 2022-05-05 12:06
What are you using to capture the sounx?  rtlsdr?  Ham Radio? etc?  Please describe your setup.

**Comment by rgleason** [comment] 2022-05-06 23:59
Scarns  I can confirm that Retrieve > Capture and picking a saved sound file does not work.
"Failed to configure capture"

**Comment by rgleason** [comment] 2022-05-07 00:10
Here is a link to some sound files.
https://2bsailing.ca/info/Weatherfax_and_shortwave_radio.php

Sound samples
http://www.jvcomm.de/soundframee.html

**Comment by SCarns** [comment] 2022-05-08 18:27
Sorry Rick. Didn't mean to drop out. I went into the yard this week and my free time evaporated. Thanks for the files, I'll check those out soon and report back.

Steve

**Comment by rgleason** [comment] 2022-05-08 19:09
Steve No problem. Also tryinf to get launched. Lots of peojects.

**Comment by rgleason** [comment] 2024-12-20 17:09
Steve,  I am back at Weatherfax.  Did you see this post? 
https://www.cruisersforum.com/forums/f134/weatherfax-plugin-19-60-0-linx-mint-missing-ui-buttons-278918.html#post3814973
PMX had success downloading sound files, and in this post he describes the whole process
https://www.cruisersforum.com/forums/f134/weatherfax-plugin-19-60-0-linx-mint-missing-ui-buttons-278918.html#post3816899
using an internet connection for the sound files, which makes it easier to test.

Also Francizka has had success retrieving SSB sound files over a radio and she wrote a simple pdf about that that is now in the plugin manual.

Is this issue still valid?

**Comment by rgleason** [comment] 2024-12-20 17:15
PS: WE have a more recent plugin up in Cloudsmith, Weatherfax 1.10.3
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.10.3+tarball

**Comment by rgleason** [comment] 2024-12-23 01:53
Steve please see weatherfax 1.10.4  or later which should be pushed to the catalog pretty soon.
If you still have problems please make another issue.
I have tested it for Windows and can do a capture. It isn't very clear, but that is probably due to it being a first for me. I am still learning.
Thanks for the report, sorry I did not get to it until now.

See https://github.com/rgleason/weatherfax_pi/issues/139#issue-1881033427

**Comment by rgleason** [comment] 2024-12-23 01:53
Closing

**Closed by rgleason** 2024-12-23 01:53 UTC
